version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
                   cd src
                   dotnet restore
      - run:
          name: Tests
          command: |
                   cd src
                   dotnet test Nhahaha.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=bin
      - run:
          name: Codecov
          command: |
                   bash <(curl -s https://codecov.io/bash) -f "src/Nhahaha.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
